SELECT NOME, ANO FROM FILMES;

SELECT NOME, ANO FROM FILMES ORDER BY ANO;

SELECT NOME, ANO, DURACAO FROM FILMES WHERE UPPER(NOME) = 'DE VOLTA PARA O FUTURO';

SELECT NOME, ANO, DURACAO FROM FILMES WHERE ANO = 1997;

SELECT NOME, ANO, DURACAO FROM FILMES WHERE ANO > 2000;

SELECT NOME, ANO, DURACAO FROM FILMES WHERE DURACAO > 100 AND DURACAO < 150 ORDER BY DURACAO;

SELECT ANO, COUNT(*) QUANTIDADE FROM FILMES GROUP BY ANO ORDER BY SUM(DURACAO) DESC; 

SELECT PRIMEIRONOME, ULTIMONOME FROM ATORES WHERE GENERO = 'M';

SELECT PRIMEIRONOME, ULTIMONOME FROM ATORES WHERE GENERO = 'F' ORDER BY PRIMEIRONOME;

SELECT FILMES.NOME, GENEROS.DESCRICAO FROM FILMES 
JOIN FILMESGENERO ON FILMES.ID = FILMESGENERO.ID_FILME
JOIN GENEROS ON FILMESGENERO.ID_GENERO = GENEROS.ID;

SELECT FILMES.NOME, GENEROS.DESCRICAO FROM FILMES 
JOIN FILMESGENERO ON FILMES.ID = FILMESGENERO.IDFILME
JOIN GENEROS ON FILMESGENERO.IDGENERO = GENEROS.ID
WHERE UPPER(GENEROS.DESCRICAO) = 'MISTÉRIO';

SELECT FILMES.NOME, ATORES.PRIMEIRONOME, ATORES.ULTIMONOME, ELENCOFILME.PAPEL FROM FILMES 
JOIN ELENCOFILME ON FILMES.ID = ELENCOFILME.IDFILME
JOIN ATORES ON ELENCOFILME.IDATOR = ATORES.ID;